version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  groups:
    pelican-dependencies:
      patterns:
      - '*'
      dependency-types: "development"
      update-types:
      - "minor"
      - "patch"
